Repository WildCodeSchool/lyon-js-03-20-p2-g4, pull requests merged in 2020-05, with the labels that each got.

#43 Feature/us10
  package-lock.json
  package.json
  src/components/User2List.js
  src/pages/MatchRoom.js
Labels: Reviewed

#44 Feature/us11
  package.json
  src/App.js
  src/components/User2List.js
  src/pages/MatchRoom.js
  src/pages/Result.js
  src/styles/Result.css
Labels: Correction done, Reviewed

#42 Feature/us14
  src/components/User1List.js
  src/components/User2List.js
  src/images/return.svg
  src/pages/MatchRoom.js
  src/styles/Button.css
Labels: Correction done, Reviewed

#46 Feature/us18
  src/pages/MatchRoom.js
  src/pages/Result.js
Labels: Correction done, Reviewed

#47 Feature/us15
  src/components/Drawer.js
  src/components/movieDetails.json
  src/images/close-draw.png
  src/images/default-avatar.jpg
  src/images/default-avatar.png
  src/images/play-icon.png
  src/images/star-empty.png
  src/images/star-full.png
  src/images/star-half.png
  src/pages/MatchRoom.js
  src/pages/Result.js
  src/styles/Drawer.css
  src/styles/HeaderSmall.css
  src/styles/Result.css
  src/styles/index.css
Labels: Changes requested

#48 Feature/us16
  src/App.js
  src/components/Match.js
  src/pages/MatchRoom.js
  src/styles/UserList.css
Labels: Correction done, Reviewed

#54 Feature/us13
  src/components/User1List.js
  src/components/User2List.js
  src/images/match-icon.png
  src/images/return.png
  src/pages/MatchRoom.js
  src/styles/Button.css
  src/styles/UserList.css
Labels: Reviewed

#55 Feature/us20
  package-lock.json
  package.json
  src/components/Drawer.js
  src/components/Match.js
  src/pages/MatchRoom.js
  src/pages/Result.js
  src/styles/MatchRoom.css
Labels: Reviewed

#57 Feature/us19
  src/App.js
  src/components/Drawer.js
  src/components/FilmCard.js
  src/components/MovieLists.js
  src/components/User1List.js
  src/components/decades.js
  src/components/genre.js
  src/components/people.js
  src/images/1960.jpg
  src/images/1970.jpg
  src/images/1980.jpg
  src/images/1990.jpg
  src/images/2000.jpg
  src/images/2010.jpg
  src/images/2020.jpg
  src/images/animation.jpg
  src/images/clintEastwood.jpg
  src/images/comedy.jpg
  src/images/drama.jpg
  src/images/francisFordCoppola.jpg
  src/images/grey-logo.png
  src/images/jackyChan.jpg
  src/images/jjAbrams.jpg
  src/images/lucBesson.jpg
  src/images/martinScorsese.jpg
  src/images/quentinTarantino.jpg
  src/images/romantic.jpg
  src/images/stanleyKubrick.jpg
  src/images/stevenSpielberg.jpg
  src/images/timBurton.jpg
  src/pages/Home.js
  src/pages/MatchRoom.js
  src/pages/Result.js
  src/styles/Drawer.css
  src/styles/Home.css
  src/styles/Result.css
Labels: Reviewed

#59 Feature/us19bis
  src/components/TrendList.js
  src/pages/Home.js
  src/pages/MatchRoom.js
  src/styles/Home.css
  src/styles/TrendList.css
Labels: Reviewed

#61 Feature/us21
  src/components/HeaderHome.js
  src/images/home-background.jpg
  src/images/movie-match-dark-background.png
  src/pages/Home.js
  src/styles/App.css
  src/styles/HeaderHome.css
  src/styles/Home.css
  src/styles/TrendList.css
  src/styles/UsersInputs.css
  src/styles/movielists.css
Labels: Reviewed

#63 Feature/us23
  src/components/History.js
  src/components/SidebarInfoDesktop.js
  src/components/User1List.js
  src/components/User2List.js
  src/images/reject-white.svg
  src/images/validate-white.svg
  src/pages/MatchRoom.js
  src/styles/History.css
  src/styles/SidebarInfoDesktop.css
  src/styles/UserList.css
Labels: Reviewed

#62 Feature/us22
  src/App.js
  src/components/MovieLists.js
  src/components/User2List.js
  src/pages/Home.js
  src/pages/MatchRoom.js
  src/pages/Result.js
  src/styles/Result.css
Labels: Reviewed

#64 Feature/us24
  src/App.js
  src/components/Button.js
  src/components/Drawer.js
  src/components/ResultHistory.js
  src/components/SidebarInfoDesktop.js
  src/components/User1List.js
  src/components/User2List.js
  src/images/movie-match-grayscale.svg
  src/images/star-full-border.png
  src/pages/MatchRoom.js
  src/pages/Result.js
  src/styles/Button.css
  src/styles/HeaderSmall.css
  src/styles/History.css
  src/styles/Result.css
  src/styles/ResultHistory.css
  src/styles/TrendList.css
  src/styles/index.css
Labels: Reviewed

#66 Feature/us26
  src/components/genre.js
  src/components/people.js
  src/images/dwayneJohnson.jpg
  src/images/jackyChan.jpg
  src/images/jjAbrams.jpg
  src/images/jodieFoster.jpg
  src/images/johnnyDepp.jpg
  src/images/morganFreeman.jpg
  src/images/mystery.jpg
  src/images/quentinTarantino.jpg
  src/images/robertDowneyJr.png
  src/images/scarlettJohansson.png
  src/images/sigourneyWeaver.jpg
  src/images/timBurton.jpg
Labels: Reviewed

#67 Issue/fix css
  public/index.html
  public/manifest.json
  src/components/HeaderSmall.js
  src/components/Match.js
  src/components/User1List.js
  src/components/User2List.js
  src/components/people.js
  src/images/flame-1.png
  src/images/flame-2.png
  src/images/flame-3.png
  src/images/stars-match.png
  src/pages/Home.js
  src/pages/MatchRoom.js
  src/pages/Result.js
  src/styles/App.css
  src/styles/Button.css
  src/styles/Drawer.css
  src/styles/FilmCard.css
  src/styles/HeaderSmall.css
  src/styles/History.css
  src/styles/Home.css
  src/styles/MatchRoom.css
  src/styles/Result.css
  src/styles/SidebarInfoDesktop.css
  src/styles/UserList.css
  src/styles/UsersInputs.css
Labels: Reviewed
